---
- import_tasks: install.yml

- name: configure users
  include_tasks: configure-groups.yml
  when: "users is defined and users not in ([], None, '', omit)"

- name: install kubernetes dashboard
  include_tasks: install-dashboard.yml
  when: microk8s_plugin_dashboard_enable
